# Generated by Django 4.1.3 on 2022-11-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource_id', models.IntegerField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.IntegerField(auto_created=True, default=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('Item2', models.TextField(max_length=200)),
                ('Item3', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Telemdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('datapoint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.datapoint')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.datasource')),
            ],
        ),
    ]
