# Generated by Django 4.1.3 on 2022-11-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='datasource_id',
            field=models.CharField(auto_created=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='info',
            field=models.CharField(auto_created=True, max_length=200),
        ),
    ]
